### ISSUE TITLE
Milestone: KV storage implement replace with `Redis`

### ISSUE THREAD

**Issue by Lonor** [Lonor/site#32]
Now this project using the CloudFlare KV as the implement of the KV storeage for user's view count.
But this service is based on the CloudFlare and it's not available with *native* CRUD queries.
I prefer using the database which is more generic and not dependent on some specific platforms / companys.
*Redis* should be a good choice - open source and simple queries like `get` / `set`.

- [x] Find a Redis service or some RaaS (Redis as a service)
- [x] Code change with `redis://` connection
- [x] Consider whether we should keep the CloudFlare KV data
- [ ] Long term solution for the Redis server with low cost

**Comment by Lonor** [comment]
/label milestone 
/label feature
/label backend
/label database

This should be EPIC level feture. T-Shirt size estimated to be XXL.
